### ISSUE TITLE
How to  Request in Controller 

### ISSUE THREAD

**Issue by LokiThor2021** [FeastFramework/feast#1]
Hi, i am just testing the framework looks good thus far. 
How can i get  the request obj in a controller class ? 
@jpresutti

**Comment by jpresutti** [comment]
You can pass it into your controller via dependency injection. See [here](https://github.com/FeastFramework/framework/blob/e04511719de589c5574975941e725b9bf1ebca3e/Controllers/CacheController.php#L65) for an example. Just use `RequestInterface` rather than `RouterInterface`.
